language: cpp
sudo: required
dist: trusty 
compiler:
- g++
- c++
os:
- linux
before_script: 
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
- g++ --version

- cmake .
script:
- make VERBOSE=1
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-5
    - g++-5
    - cmake 
    - libboost1.55-all-dev
notifications:
  email: false
