language: cpp
sudo: required
dist: trusty 
compiler:
- g++
- c++
os:
- linux
before_script: 
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
- g++ --version
- wget http://releases.llvm.org/3.8.1/clang+llvm-3.8.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
- tar xf clang+llvm-3.8.1-x86_64-linux-gnu-ubuntu-14.04.tar.xz
- wget https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.gz
- tar xf boost_1_61_0.tar.gz
- export PATH=${PWD}/boost_1_61_0/bin:${PWD}/clang+llvm-3.8.1-x86_64-linux-gnu-ubuntu-14.04/bin:$PATH
- export LD_LIBRARY_PATH=${PWD}/boost_1_61_0/lib:${PWD}/clang+llvm-3.8.1-x86_64-linux-gnu-ubuntu-14.04/lib:$LD_LIBRARY_PATH
- cmake -DLLVM_DIR=clang+llvm-3.8.1-x86_64-linux-gnu-ubuntu-14.04/share/llvm/cmake/ .
- cmake -DBOOST_ROOT=boost_1_61_0/ .
script:
- make VERBOSE=1
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - cmake 
    - icu
notifications:
  email: false
